version: "3"

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    volumes:
      - mssql-data-volume:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=<password>
    ports:
      - 1433:1433
  app:
    build:
      context: .
      dockerfile: src/TodoList.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 8080:80
    depends_on:
      - db

volumes:
  mssql-data-volume:
