version: '3.4'

services:
  db:
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${TODOLIST_DB_PASSWORD}
    ports:
      - 1433:1433
    volumes:
      - mssql-data-volume:/var/opt/mssql
  app:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Data Source=db;Initial Catalog=ToDoList;MultipleActiveResultSets=True;Persist Security Info=True;User ID=sa;Password=${TODOLIST_DB_PASSWORD}
      - Jwt__Secret=peRhtr7oth7nh98rtx78Tdy0g98graKfYrovjhaz5dX75h56trOdKvnghruGYdxm
      - Cors__Origins=https://localhost:44328
      - SendGrid__ApiKey=${TODOLIST_SENDGRID_APIKEY}
      - LinkedIn__ClientSecret=${TODOLIST_LINKEDIN_CLIENTSECRET}
      - LinkedIn__ClientId=${TODOLIST_LINKEDIN_CLIENTID}
      - Google__ClientSecret=${TODOLIST_GOOGLE_CLIENTSECRET}
      - Google__ClientId=${TODOLIST_GOOGLE_CLIENTID}
      - Github__ClientSecret=${TODOLIST_GITHUB_CLIENTSECRET}
      - Github__ClientId=${TODOLIST_GITHUB_CLIENTID}
      - Facebook__AppSecret=${TODOLIST_FACEBOOK_APPSECRET}
      - Facebook__AppId=${TODOLIST_FACEBOOK_APPID}
    ports:
      - 8080:80

volumes:
  mssql-data-volume:
